import Root from './approval-request.svelte';
import Content from './approval-request-content.svelte';
import Header from './approval-request-header.svelte';
import Status from './approval-request-status.svelte';
import Icon from './approval-request-icon.svelte';
import Risk from './approval-request-risk.svelte';
import Title from './approval-request-title.svelte';
import Description from './approval-request-description.svelte';
import Details from './approval-request-details.svelte';
import Footer from './approval-request-footer.svelte';
import Cancel from './approval-request-cancel.svelte';
import Confirm from './approval-request-confirm.svelte';
export { Root, Content, Header, Status, Icon, Risk, Title, Description, Details, Footer, Cancel, Confirm };
