export const components = [
	'accordion',
	'alert',
	'alert-dialog',
	'approval-request',
	'attachment',
	'avatar',
	'badge',
	'breadcrumb',
	'button',
	'card',
	'checkbox',
	'code-block',
	'collapsible',
	'color-picker',
	'combobox',
	'command',
	'context-menu',
	'conversation',
	'copy-button',
	'dropdown-menu',
	'fullscreen-nav',
	'gauge',
	'hover-card',
	'input',
	'label',
	'markdown',
	'message',
	'modal',
	'pagination',
	'popover',
	'progress',
	'prompt-composer',
	'radio-group',
	'reasoning',
	'response-stream',
	'scroll-area',
	'select',
	'sheet',
	'shortcut',
	'skeleton',
	'slider',
	'spinner',
	'switch',
	'tabs',
	'textarea',
	'toast',
	'toggle',
	'toggle-group',
	'tool',
	'toolbar',
	'tooltip'
] as const;

export const sanitizeComponent = (name: string) => {
	return name
		.split('-')
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');
};
